### PR TITLE
Trinity backend

### PR DESCRIPTION
**Pull request by OmarIthawi**
Trinity OAuth backend.

To be installed as an extra requirement, by using the unmodified Python Social Auth. This backend should work on both Python Social Auth (used in Ficus) and Social Core (used in Ginkgo).

### TODO

 - [x] Add pep8 and pyflakes
 - [ ] ~Coverage, do we need it?~
   * I'll postpone this one.

### Open Questions
 - [x] What does `# DEFAULT_SCOPE = ['email']` mean and why it's commented?
 - [x] Why `REDIRECT_STATE` is set to `False`?
      - We'll keep it as-is, till we reach that [Trinity card enrollment](https://trello.com/c/Xi2XGHCy/2311-16-support-enrollment-while-doing-sso-redirects-for-trinity)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
[(6) Trinity upgrade: Port and test SSO customizations to Ficus](https://trello.com/c/NyzgmrBS/2670-6-trinity-upgrade-port-and-test-sso-customizations-to-ficus)

**Comment by OmarIthawi** [comment]
@melvinsoft could you please take a look at the open questions above?

@amirtds please take a look at the backend in general.

**Comment by melvinsoft** [comment]
@OmarIthawi I've been taking a look at the code trying to refresh my memory. 

`DEFAULT_SCOPE`: To be honest, I think we're not using default scopes for Trinity, because I'm not sure if the backend is using permission based on scopes. I think it worth to check with them this, but I've run the OAuth login process, and looks like we're not sending the `scope` parameter.

`REDIRECT_STATE`: I've found this entry in the docs: https://github.com/python-social-auth/social-docs/blob/master/docs/backends/implementation.rst#oauth2

Looks like the parameter is more related to the state parameter, that usually is sent just to verify that is returned by the provider, and check the authenticity of the request. Looks like it should be safe to change it to True.

Please let me know, if you need we can jump in a quick call. Also if is necessary I can set up the project locally again to debug.

**Comment by OmarIthawi** [comment]
Thanks @melvinsoft! I'll keep it as-is. Will consider the backend done for now. 

I'll integrate it with the staging instance and test it. Will amend only when needed.

**Review by bryanlandia — COMMENTED** [review]
I don't see any issues with this, @OmarIthawi, though I don't have a lot of understanding about using Py Social Auth. I do see that build 33 is failing in Travis where earlier builds passed.  Do you know why?

**Comment by OmarIthawi** [comment]
Thanks @bryanlandia. It was a minor style issue. I'll merge this once the CI has green lights.

Will follow up with another PR when Trinity provides feedback.

**Pull request merged**
